version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "14:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
