language: php
php:
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - phpenv rehash

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/phpunit --verbose --colors --coverage-text --coverage-clover ./build/logs/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then vendor/bin/phpunit --verbose --colors; fi
